### ISSUE TITLE
Api port should be exposed by default.

### ISSUE THREAD

**Issue by vskubriev** [cdalvaro/docker-salt-master#40]
As a new user I just edit compose file and bring up a container. But unfortunately forget about exposing api port in docker compose. That's why I faced with ssl error when trying to connect to api. 

Should be added at:
https://github.com/cdalvaro/docker-salt-master/blob/581808b8fa059b56ad7b0bb8a58ea95c7f202c0f/docker-compose.yml#L12

Of course it can be added as commented row, because it is not enabled by default. But  I think it should be. That's just an example.

@cdalvaro what do you think about this ?

**Comment by cdalvaro** [comment]
Hi @vskubriev,

Thank you for reporting this!
I see right adding the salt-api port to the docker-compose.yml, but commented.

As you've said, since the service is not enabled by default, it could be confusing to open the port but leave the service disabled.

So I'll update the docker-compose.yml with the salt-api settings commented. This way anyone who wants to enable the service will only have to uncomment those lines and set the password.

I will also update REAMDE.md and Wiki to help other people with this!

Thank you again for your time and help!
