### ISSUE TITLE
Add support for configurating the reactor in master config

### ISSUE THREAD

**Issue by dmlambea** [cdalvaro/docker-salt-master#58]
As per the documentation, there is a way for telling the master to sync custom types on minions' start. Please refer to: https://docs.saltproject.io/en/latest/topics/reactor/index.html#minion-start-reactor

It would be good to have a config option and directory mapping for configuring the reactor, much like other options are (mounting the keys, roots, etc).

An alternative could be enhancing the config system so a master config template (or zero or more small config files like Apache's conf.d/* files, for example) can be used. This way, future or yet unsupported options could be covered easily.

**Comment by cdalvaro** [comment]
Hi @dmlambea! Thank you for opening this issue!

Right now, you can set your own _reactor_ settings by creating a `reactor.conf` file inside the `config` directory and mounting it:

```sls
# config/reactor.conf
reactor:
  - 'salt/minion/*/start':
    - /srv/reactor/sync_grains.sls
```

`/srv` directory is _symlinked_ to `/home/salt/data/srv`, but you can also specify `/home/salt/data/srv/reactor/sync_grains.sls` instead of `/srv/reactor/sync_grains.sls`.

```sh
docker run --name salt_stack --detach \
    --publish 4505:4505 --publish 4506:4506 \
    --volume $(pwd)/roots/:/home/salt/data/srv/ \
    --volume $(pwd)/config/:/home/salt/data/config/ \ # Mounts config/ dir
    cdalvaro/docker-salt-master:latest
```

This way, you can add your `sync_grains.sls` file to `roots/reactor`:

```sls
# roots/reactor/sync_grains.sls
sync_grains:
  local.saltutil.sync_grains:
    - tgt: {{ data['id'] }}
```

And that should do the trick. I use this method for my `start.sls` reactor.

Please let me know if this method does not fit your requirements, or if you see any way to improve this support.
Anyway, I will add this case to the documentation for better support.

**Comment by dmlambea** [comment]
Hi @cdalvaro

It worked, thank you!
